import Head from "next/head";
import { Rubik } from "next/font/google";
import clsx from "clsx";
import Component from "~/components/A";

const font = Rubik({
  subsets: ["latin-ext"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav
        className={clsx(
          font.className,
          "flex items-center justify-between bg-lime-600 px-20 py-4 text-xl font-bold text-gray-50",
        )}
      >
        <div className="">
          <span className="font-mono">Clsx</span> showcase
        </div>
      </nav>
      <main
        className={clsx(
          "flex min-h-screen flex-col items-center justify-center",
          font.className,
        )}
      >
        <Component />
      </main>
    </>
  );
}
